### ISSUE TITLE
Duplicated symbol `gcov_flush` (SPM, Xcode 12)

### ISSUE THREAD

**Issue by natalia-osa** [realm/realm-cocoa#6814]
## Goals

To be able to compile project with Realm dependency added via SPM using Xcode 12.

## Expected Results

The dependency (realm) shouldn't have duplicated symbols.

## Actual Results
While locally I can make things happen, on CI (Bitrise) I receive following logs. It rather looks like an issue from Realm than from Bitrise, but please correct me if I'm wrong.

```
[...]
▸ Compiling MySomethingViewCell.swift
▸ Linking MyAppName
❌  duplicate symbol '___gcov_flush' in
> Realm.o
> RealmCore.o
❌  ld: 1 duplicate symbol for architecture x86_64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
and in detailed logs:
```
duplicate symbol '___gcov_flush' in:
    /Users/vagrant/Library/Developer/Xcode/DerivedData/MyAppName-bovnkatmzqfuxmgxfczktvjiwuqp/Build/Products/Staging-iphonesimulator/Realm.o
    /Users/vagrant/Library/Developer/Xcode/DerivedData/MyAppName-bovnkatmzqfuxmgxfczktvjiwuqp/Build/Products/Staging-iphonesimulator/RealmCore.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Steps for others to Reproduce

Hard to say, especially since I can't reproduce it locally, where it's working. Maybe just the step in Bitrise where it fails:
```
- xcode-test:
          inputs:
            - project_path: $XCODEBUILD_PROJECT
            - scheme: $XCODEBUILD_SCHEME
            - xcodebuild_test_options: $XCODEBUILD_OPTIONS
            - simulator_device: iPad Air (4th generation)
            - generate_code_coverage_files: 'yes'
            - should_build_before_test: 'no'
            - output_tool: 'xcpretty'
```

## Code Sample

No sample code, since it fails on the compilation of the library.

## Version of Realm and Tooling

Realm framework version: 5.4.4

Realm Object Server version: None

Xcode version: 12.0

iOS version: iOS 11 and newer (trying to run tests on a simulator of iPad Air 4Gen, iOS 14)
OSX version: macOS 10.15.6 (Catalina) on CI (same version locally on my machine where it compiles)

Dependency manager + version: SPM included with Xcode
SPM rules for this library- repository (https://github.com/realm/realm-cocoa.git), version EXACT to 5.4.4 (but tested 5.4.3 as well, and it also didn't work). When importing via SPM I ticked both Package Products: Realm and RealmSwift. By the way, you're missing installation via SPM in your documentation (https://realm.io/docs/swift/latest#installation).
